### PR TITLE
Add ability to save results to TSV

### PR DESCRIPTION
**Pull request by bradym**
Nice job with this project! I thought it'd be nice to track progress over time, so I added a feature to do just that. Please let me know if you have any questions or see any issues with how I implemented it.

### CODE REVIEW

**Comment by qwhex** [comment]
I agree with balzss about the timeouts. Also, calcStats should definitely be a pure function, so it should return the object, not update it as a side-effect.

**Comment by bradym** [comment]
Good feedback, thanks!

Rather than calling `saveStats` from `printStats`, I created a new function to wrap all of the things that should happen when a test is done. I think this makes the code easier to follow as it keeps functions limited to doing a single unit of work.

I also updated `calcStats` to take a parameter and return the object. 

> Maybe we can insert the next stats item before the first worse wpm / accuracy, so we can determine if it's a new record or not without reading the whole file.

My original thought was to leave the interpretation of the data up to the user. It depends on how much you want to make this tool do. Determining if a set of results is a new record could get messy when considering all the variables. Especially considering the length of the test and the complexity of the wordlist.

For example if my word list for one test is something like: "the of and to a in that", the accuracy and wpm on 
that word list probably should not be considered a new record if I've done another test using a wordlist like 
"abdominally abdominoanterior abdominocardiac abdominocentesis abdominocystic abdominogenital abdominohysterectomy".

**Comment by qwhex** [comment]
True, although it's highly unlikely to get words like those as we shuffle the worldist before presenting it. 

Thanks for the fixes, will get back to you from my computer to ⛜ merge (and check your changes more thoroughly).

**Comment by bradym** [comment]
> For different wordlists: we could save the stats as separate files / wordlist.

It might be worth doing that in a separate ticket/pr as there are a number of ways it could be implemented and might be something that is worth putting more thought into. It just depends on how simple/complex you want to make it and how much you want this tool to do.

**Comment by qwhex** [comment]
What can we write into package.json as your name, url, email? Thanks.

**Pull request merged**
