### PR TITLE
Clear cli on start

### PR DESCRIPTION
**Pull request by harryparkdotio**
Clear cli on start

### CODE REVIEW

**Comment by qwhex** [comment]
Hi,
Thanks for your pull request! Why do you think it's a good idea to clear the terminal on start? Genuine question, zero sarcasm.

**Comment by harryparkdotio** [comment]
By clearing the cli, you can guarantee the placement of words time after time in terms of height, rather than keeping the output and solely adding below, which means the height placement changes

**Comment by qwhex** [comment]
I will check out your solution later to see what you mean (currently I'm on my phone) but my first guess is that your installation is somehow misbehaving as we only display two lines of input at a time and we clear/update the lines in question periodically. Does your experience correspond with the supplied demo gif?

**Comment by harryparkdotio** [comment]
Sorry, you must've misunderstood what I meant. 

Like this (see image)
screen shot 2018-04-17 at 5 08 24 pm

**Comment by balzss** [comment]
Hi, thanks for the PR! Two things: please try to follow the coding style next time (spaces instead of tabs, avoid fn calls on top level and use named functions) and I think having the terminal cleared is not something everybody would want (for example, I would prefer it not to clear mine) so as long it's not a "universal need" I don't want to include it but let me know if I forgot something.

**Pull request closed without merging**
